// <auto-generated />
namespace EstateAgents.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class VendorId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VendorId));
        
        string IMigrationMetadata.Id
        {
            get { return "202003081534258_VendorId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
